name: Vale Linting
on: [pull_request]

jobs:
  vale:
    name: Runner - Vale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Vale
        run: |
          # Скачиваем и устанавливаем Vale напрямую
          curl -LO https://github.com/errata-ai/vale/releases/download/v2.28.0/vale_2.28.0_Linux-64-bit.tar.gz
          tar -xvzf vale_2.28.0_Linux-64-bit.tar.gz
          sudo mv vale /usr/local/bin/
          vale --version

      - name: Run Vale
        run: |
          vale --config=.vale.ini --output=line --no-exit docs/